spring:
  profiles:
    active: dev
  cache:
    jcache:
      config: classpath:ehcache.xml

cache:
  settings:
    maxEntries: 1000
    liveTimeInSec: 300




exchangeRate:
  baseUrl: 'https://api.exchangeratesapi.io/latest'